config/routes.rb
Rails.application.routes.draw do
  devise_for :users

    root 'albums#index'

    resources :users do
      resources :albums do
        collection do
          get 'my_album'
        end
        member do
          get 'make_cover'
          get 'share_album'
          get 'sent_album'
        end
        resources :photos do
          resources :comments
        end
      end
      resources :friends do
        member do
          get 'respond'
        end
      end
    end

      

end

app/models/album.rb
class Album < ActiveRecord::Base
	belongs_to :user
	has_many :photos, dependent: :destroy
	accepts_nested_attributes_for :photos, allow_destroy: true
	validates :name, :description, :presence => true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!

  def index
    @friends = Friend.where('(friend_id = ? OR user_id = ?) AND status = "Approve"',current_user.id, current_user.id)
    @user_id = @friends.pluck(:user_id, :friend_id).flatten
    @users = User.where(id: @user_id).where.not(id: current_user.id).pluck(:id).uniq
    @albums = Album.where(user_id: @users, publish: true).paginate(page: params[:page], per_page: 30)
  end

  def new
    @album = Album.new
    @album.photos.new
  end
 
  def show
    @album = Album.find(params[:id])
    @photos = @album.photos
  end

  def edit
    @album = current_user.albums.find(params[:id])
    if @album.blank?
      flash[:error]="Unauthorise user"
      redirect_to my_album_user_albums_path(current_user)
    end  
  end	

  def create
    @album = current_user.albums.new(album_params)
      if @album.save
       redirect_to my_album_user_albums_path(current_user),notice: 'Album was successfully created.'
      else
       flash[:error] = @album.errors.full_messages.join('.').html_safe
       render 'new' 
      end  	
  end

  def update
    @album = current_user.albums.find(params[:id])
  	if @album.update(album_params)
      @album.photos.each do |photo|
        if photo.changed? && photo.comments.present?
          photo.comments.destroy_all
        end
      end   
      redirect_to my_album_user_albums_path(current_user), notice: 'album was successfully updated.'
    else
      flash[:error] = @album.errors.full_messages.join('.').html_safe
      redirect_to edit_user_album_path(current_user,@album)
    end  
  end	

  def destroy
    @album = current_user.albums.find(params[:id])
    if @album.destroy
      redirect_to my_album_user_albums_path(current_user), notice: 'album was successfully deleted.'
    else
      flash[:error] = "Not deleted"
    end 
  end

  def my_album
    @albums = current_user.albums.paginate(page: params[:page], per_page: 30)
  end  

  def make_cover
    @album = current_user.albums.find(params[:id])
    @album.photos.update_all(cover_photo: false)
    @photo = @album.photos.find(params[:photo_id])
    if @photo.update(cover_photo: true)
      redirect_to my_album_user_albums_path(current_user), notice: 'Cover page is set.'  
    end 
  end 

  def  share_album
    @album = current_user.albums.find(params[:id])
  end

  def  sent_album
    @user = User.find_by_email(params[:email])
    @album = current_user.albums.find(params[:id])
    if @user.present? 
      AlbumMailer.mail_my_album(@user, @album).deliver_now 
      redirect_to my_album_user_albums_path(current_user), notice: 'Album send successfully'
    else
      flash[:error] ="Invalid email"
      redirect_to share_album_user_album_path(current_user.id, @album.id)
    end  
  end   

  private		

  def album_params
      params.require(:album).permit(:name, :description, :publish, :photos_attributes => [:id, :album_id, :image, :user_id, :_destroy])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
  def album_cover_photo(album)
  	@album = album
  	@photo = @album.photos.where(cover_photo: true).first
  	if @photo.present?
      @photo.image.url
	  elsif @album.photos.present?
	  @album.photos.first.image.url
	  else
	   image_url("default.jpeg")
	  end
  end
end

app/views/albums/_delete_photo.html.erb
<% @photos = album.photos %>
<% unless album.photos.blank? %>
  <% album.photos.each do |photo| %>
      <div class="img-thumbnail">
        <div><%= link_to (image_tag photo.image.url, size: "220x200"), user_album_photo_path(current_user.id, @album.id, photo.id) %></br>
        <% if @album.user == current_user%>
          <%= link_to 'Make cover', make_cover_user_album_path(current_user.id, @album.id, photo_id: photo.id)%>|
          <%= link_to 'Delete', '#', data: {id: photo.id }, :class => "destroy_photo" %>
        <% end %>
        </div>  
      </div>  
    <% end %>
  <% else %>
  <p>No photos are presents in this album.</p>
<% end %>

<script type="text/javascript">
  $('.destroy_photo').click(function() {
    var id = $(this).data('id');
    var answer = confirm ("Are you sure");
    if (answer) {
      $.ajax({
          type: "DELETE",
          url: "/users/<%= current_user.id %>/albums/<%= @album.id %>/photos/"+id
      }).complete(function(json){
        $('#delete_photo').html(json.responseText);
      });
    }
  });
</script>

app/views/albums/_form.html.erb
<%= form_for ([current_user, @album]), html: {:class => "form-horizontal center"} do |f| %>
  <div class="row col-sm-6">
    <h3>New Album</h3>
    <div>
      <%= f.text_field :name, placeholder: "Enter name of album", :class => "form-control "  %></br>
    </div>
    <div>
      <%= f.text_area :description, placeholder: "Description", :class => "form-control "  %></br>
    </div>
    <div>
      <%= f.label "Publish"%>
      <%= f.check_box :publish %>
    </div>
    <h3>Add Photos</h3>
    <div>
      <%= f.fields_for :photos do |photo| %>
        <%= render 'photo_fields', f: photo %>
      <% end %></br>
      <%= link_to_add_association 'add photo', f, :photos, :class => "btn btn-small btn-primary" %>
    </div></br>
    <div>
      <%= f.submit :class => "btn btn-success" %>
    </div>
  </div>  
<% end %>

app/views/albums/_photo_fields.html.erb
<div class='nested-fields'>
    <%= image_tag f.object.image.url(:thumb) if f.object.image? %>
	<%= f.file_field :image %>
	<%= f.hidden_field :user_id, :value => current_user.id %>
	<%= link_to_remove_association 'Remove', f %>
</div>

app/views/albums/edit.html.erb
<%= render 'form' %>

app/views/albums/index.html.erb
<table class="table table-striped table-bordered">
  <tbody>
      <% @albums.each do |album|%>
        <div class="img-thumbnail">
          <div>
            <%=link_to image_tag(album_cover_photo(album), size: "170x120"),user_album_path(current_user.id, album.id)%>
          </div>
          <div>
            <%= album.name+' by '+album.user.user_name %> 
          </div>
        </div> 
      <% end %>   
  </tbody>
</table>
<%= will_paginate @albums %>

app/views/albums/my_album.html.erb
<table class="table table-striped table-bordered">
    <% @albums.each do |album| %>
      <div class="img-thumbnail">
        <div>
          <%=link_to image_tag(album_cover_photo(album), size: "170x120"),user_album_path(current_user, album.id)%></br>
        </div>
          <div>
            <%= album.name %> |
            <%= album.description %>
          </div>
          <div style="border-top: #e5e5e5 1px solid">
            <div class="col-lg-1"><%= link_to 'Edit', edit_user_album_path(current_user, album.id) %></div>
             <div class="col-lg-1"><%= link_to 'Destroy', user_album_path(current_user, album.id), method: :delete, data: { confirm: 'Are you sure?' } %></div></br>
              <div style="border-top: #e5e5e5 1px solid"><%= link_to 'Share it', share_album_user_album_path(current_user.id, album.id) %></div>
          </div>
          
          
      </div>
    <% end %>
</table>
<%= will_paginate @albums %>

app/views/albums/new.html.erb
<%= render 'form' %>

app/views/albums/share_album.html.erb
<p>Enter email address to send album</p>
<%= form_tag sent_album_user_album_path(current_user, @album), method: :get do %>
  <div class="form-group">
    <%= email_field_tag 'email'%>
  </div>
  <div class="form-group">
    <%= submit_tag 'Share' %>
  </div>
<% end %>

app/views/albums/show.html.erb
<div>
  <div>
	<strong><%= @album.name %></strong>
	<strong style="margin-left: 500px"><%= "Description: "+@album.description %></strong>
  </div>
 <div id="delete_photo">
    <%= render :partial => 'delete_photo', :locals => {album: @album} %>
  </div> 
</div>  