config/routes.rb
Rails.application.routes.draw do
  devise_for :users

    root 'albums#index'

    resources :users do
      resources :albums do
        collection do
          get 'my_album'
        end
        member do
          get 'make_cover'
          get 'share_album'
          get 'sent_album'
        end
        resources :photos do
          resources :comments
        end
      end
      resources :friends do
        member do
          get 'respond'
        end
      end
    end

      

end

app/views/layouts/_header.html.erb
<% if current_user.present? %>
  <%= link_to 'New album', new_user_album_path(current_user.id)%> |
  <%= link_to 'All albums', user_albums_path(current_user.id)%> |
  <%= link_to 'Edit Profile', edit_user_path(current_user.id)%> |
  <%= link_to 'Logout', logout_users_path%>
<% else %> 
    <%= link_to 'Sign up', new_user_path %>
    <%= link_to 'Sign in', sign_in_users_path%>
<% end %>  

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Gralbum" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        </button>
        <a class="navbar-brand" href="#">Gralbum</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <% if current_user.present? %>
            <div class=" navbar-brand " style="margin-left: 100px"> Welcome <%= current_user.first_name %> </div>
            <ul class="navbar-right ">
              <div class=" navbar-brand"><%= link_to 'New album', new_user_album_path(current_user.id) %> | </div>
              <div class=" navbar-brand"><%= link_to 'All albums', user_albums_path(current_user.id)%> | </div>
              <div class=" navbar-brand"><%= link_to 'My album', my_album_user_albums_path(current_user) %> | </div>
              <div class=" navbar-brand"><%= link_to 'Friends', user_friends_path(current_user.id) %> | </div>
              <div class=" navbar-brand dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
                <ul class="dropdown-menu">
                 <li class="navbar-brand"><%= link_to 'Edit Profile', edit_user_registration_path %></li>
                 <li class="navbar-brand"><%= link_to 'View Profile', user_path(current_user.id) %></li>
                 <li class="navbar-brand"><%= link_to 'Logout', destroy_user_session_path, :method => 'delete'%></li>
                </ul> 
              </div>
           <% else %> 
             <%= link_to 'Sign up', new_user_registration_path %>
             <%= link_to 'Sign in', new_user_session_path %>
           <% end %>
          </ul>
        </div>
      </div>
    </div>  
    <div class="container">
      <div class="row">
      <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->


    </div> <!-- /container -->

  </body>
</html>